### ISSUE TITLE
login nicht möglich

### ISSUE THREAD

**Issue by Marcel1993** [chokdee/myTTR#3]
Premium account vorhanden. User+pass korrekt

**Comment by chokdee** [comment]
Mytt ist zur Zeit offline.

**Comment by Marcel1993** [comment]
Der serverumzug ist schon beendet und mytt funktioniert. Die APP nicht

mit freundlichen Grüßen

Marcel1993

Mytt ist zur Zeit offline.

—
Reply to this email directly or view it on GitHub
<https://github.com/chokdee/myTTR/issues/3#issuecomment-75963098>.

**Comment by chokdee** [comment]
Hallo Marcel1933,
funktioniert bei mir (auf drei Telefonen getestet), welche Meldung bekommst du denn?
Hast du dich bereits vorher einloggen können?
Wenn nicht, propbier mal dein Passwort auf mytt zu ändern und dich dann erneut einzuloggen.

Gruß
Jürgen

**Comment by Marcel1993** [comment]
" login war nicht erfolgreich. Hast du einen premium account? "

Passwort Änderung hilft nicht...

Ich habe ein LG nexus 5..

mit freundlichen Grüßen

Marcel
Am 25.02.2015 15:18 schrieb "chokdee" <notifications@github.com>:

**Comment by chokdee** [comment]
Hi Marcel,

kannst du mir die HTML Seite von http://www.mytischtennis.de/community/index nach dem Login zur Verfügung stellen?

Gruß
Jürgen

**Comment by Marcel1993** [comment]
Wie mache ich das ?

mit freundlichen Grüßen

Marcel Köllmann
Am 25.02.2015 15:27 schrieb "chokdee" <notifications@github.com>:

**Comment by chokdee** [comment]
Du loggst dich auf mytt.de rufst http://www.mytischtennis.de/community/index auf und speicherst die Seite bei dir auf dem Computer.
Dann kannst du die Seite hier in Github hochladen. (Unten gibt es da einen Link "selecting them")

**Comment by Marcel1993** [comment]
Hier die HTML-Seite, entschuldige die verspätete Antwort!

mit freundlichen Grüßen

Marcel Köllmann

2015-02-26 12:09 GMT+01:00 chokdee <notifications@github.com>:

**Comment by chokdee** [comment]
Hallo Marcel,

leider hat das nicht geklappt. Am besten du schickst es mir direkt nach myttrinfo@gmail.com

Gruß
Jürgen
