### ISSUE TITLE
Make non-free dependencies optional

### ISSUE THREAD

**Issue by krt16s** [chokdee/myTTR#7]
Your latest release contains both, play-services and crashlytics. Both are non-free sofware, could provide a gradle build flavor, that does not rely on them?

**Comment by chokdee** [comment]
crashlytics is free
other I think I have removed already
why you need it?

**Comment by krt16s** [comment]
crashlytics: free as in freedom? E.g. is there the sourcecode of crashlytics available under a free software license (apache2, gpl, mit, etc.)?

**Comment by chokdee** [comment]
Hi krt16s,
I don't who you are and why you so unpolite like this.
So first try to be polite to me and and second you do your own branch and build by yourself.

**Comment by krt16s** [comment]
Mal auf deutsch, damit da nicht irgend ein Sprach-Fuck-Up passiert: Ich wollte nicht unhöflich sein, wenn das so angekommen ist, tut mir das leid (Wo genau denkst du denn, dass ich das war? Mein Englisch ist leider nicht so gut, was solche Feinheiten angeht.).

Play-services und Crashlytics sind "nicht freie" Software, d.h. der Quelltext ist entweder nicht verfügbar oder lizenztechnisch eingeschränkt, siehe z.B. https://www.gnu.org/philosophy/free-sw.html . Die Frage war, ob es möglich ist eine "gradle build flavour" bereitzustellen, die diese Software nicht benötigt. Der Grund dahinter ist, dass nicht-freie Software nicht komplett aus den Quellen gebaut werden kann -- eine Grundvorraussetzung für verlässliche Software.

Sorry nochmals, wenn ich irgendwo unhöflich war.

**Comment by chokdee** [comment]
Hallo Boris,
Na ja zunächst einmal begüsst man jemanden, wenn man ein Nachricht schreibt.

Und ja ich habe dich bereits vorher verstanden was du meinst.
Play Service sollte eigentlich nicht mehr drin sein. Aber ich schaue nochmal. Bei Crashalytics wird der FREIE Cloudservice benutzt.
Ich sehe zur Zeit keinen Grund den auszubauen oder einen extra Build dafor bereitzustellen.
Du kannst es ja gerne selbst machen und ich integriere es dann später.

Mal ne andere Frage wofür benötigst du das denn?

Gruß
Jürgen

**Comment by krt16s** [comment]
unhöflich: Mh, ja, okay.. Issue-Tracker sind bei mir weniger "Nachrichten" als Tatsächlich nüchterne Statements.. evtl. turn ich zu viel auf verschiedenen Trackern rum, dass sich da mein Benehmen etwas eingeschliffen hat. Sorry.

crashlytics: frei ist hier kostenlos

warum: Weil (ich vermute du?) die App bei F-Droid eingereicht hast, siehe https://f-droid.org/forums/topic/myttr/ . Wir können kein Update machen, wenn nicht-freie Abhängigkeiten drin sind :/

**Comment by chokdee** [comment]
Ja stimmt. Das kann da inzwischen auch wieder raus, da ich meine App in den Playstore hochgeladen habe

**Comment by krt16s** [comment]
Schade, aber okay. Ich schieb die App dann ins Archiv.
