### ISSUE TITLE
Avast meldet myTTR 2.6.2. als verdächtige Datei

### ISSUE THREAD

**Issue by marco-IT** [chokdee/myTTR#8]
Hallo.

Avast meldet myTTR 2.6.2. als verdächtige Datei - siehe Screenshot:
https://drive.google.com/open?id=1kBffAlo-duT6OwvWIAYQEtxMvSd7xTkGdg

Mit besten Grüßen,
Michael.

**Comment by chokdee** [comment]
Hallo Michael,

Doofes Antivirus Programm würde ich mal sagen ;-)

Keine Ahnung wie Avast darauf kommt, aber das einzige was myTTR macht sind Internetzugriffe auf mytischtennis.de und click-tt. Sonst nichts.

Gruß
Jürgen
